#!/bin/bash

mkdir -p ~/.local/share/fonts
cp assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf ~/.local/share/fonts/

python3 -m venv .env
source .env/bin/activate
pip install -r requirements.txt
